### ISSUE TITLE
installation instructions missing

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia-contrib/aurelia-typed-observable-plugin#2]
Please add info on npm blah blah

cli blah blah
webpack blah blah
jspm..

(-:
and keep rocking!!!

**Comment by bigopon** [comment]
`observable` and `bindable` are normal function, so we use it as if we import it from aurelia. Because of that, it was kind of hard to describe how to install it like we would in a normal aurelia plugin...

**Comment by Alexander-Taran** [comment]
Nah.. the usual stuff
```
npm i aurelia-typed-observable-plugin
```

**Comment by bigopon** [comment]
Thanks, it has been added 👍
