### ISSUE TITLE
Plugin is using packages not declared as dependencies in package.json

### ISSUE THREAD

**Issue by GabrielMancik** [aurelia-contrib/aurelia-typed-observable-plugin#3]
Namely aurelia-logging, aurelia-templating, aurelia-metadata.

**Comment by bigopon** [comment]
https://github.com/aurelia-contrib/aurelia-typed-observable-plugin/commit/d45f9b00c1c96ed72b226c1981d66739263d2e3b

**Comment by bigopon** [comment]
Thanks for reporting.
