### ISSUE TITLE
Support Typings

### ISSUE THREAD

**Issue by petronellius** [aurelia-contrib/aurelia-typed-observable-plugin#6]
Even though Typings is now deprecated way of managing Typescript definition files, it can still be useful to support it for some projects.
Simple just add typings.json
`{
  "name": "aurelia-typed-observable-plugin",
  "main": "dist/types/index.d.ts"
}`

**Comment by bigopon** [comment]
@petronellius Would be nice if you can help with this one as well 😀

**Comment by petronellius** [comment]
@bigopon Ok:)

**Comment by bigopon** [comment]
Fix has been released, thanks you !
