### ISSUE TITLE
Aurelia-templating update causes a compile issue in patches.d.ts.

### ISSUE THREAD

**Issue by OtherLeadingBrand** [aurelia-contrib/aurelia-typed-observable-plugin#9]
A recent update to aurelia-templating appears to have created a compile time issue with this library:

```
node_modules/aurelia-typed-observable-plugin/dist/types/patches.d.ts:8:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'name' must be of type 'any', but here has type 'string'.

8         name: string;
          ~~~~

  node_modules/aurelia-templating/dist/types/aurelia-templating.d.ts:1568:2
    1568  name: any;
          ~~~~
    'name' was also declared here.
```

As evidenced in the error message, aurelia-templating is now defining BindableProperty.Name as an any instead of a string.

It appears to be due to [this change ](https://github.com/aurelia/templating/pull/705)in the aurelia-templating library made to handle [this vulnerability issue in the aurelia-framework](https://github.com/aurelia/framework/issues/992):

**Comment by bigopon** [comment]
@OtherLeadingBrand thanks for reporting the issue. I'll be having a fix for this soon.

**Comment by bigopon** [comment]
@OtherLeadingBrand version `0.5.0` that contains the fix for this has been published to npm. Thanks again.
